### PR TITLE
Improve the drag/drop, completed translation (currently support english & vietnamese)

### PR DESCRIPTION
**Pull request by dohoangtung**
I did some improvement, please review and merge!

Thanks.

### CODE REVIEW

**Comment by dohoangtung** [comment]
Please change the opacity of header bar back to 0 as I've missed it
file: form-builder.scss
...
  .toolbar-header {
          opacity: 0; // visible

**Comment by Kiho** [comment]
Thanks for nice PR, most of parts are looks good but it brought  some behavior change and bugs.

1. Move component to other slot in multi column component is blocked, now you must delete component in target before move.
2. Swap component between in multi column component is blocked, component in target temporally placed out side before swap - this is inconvenient.
3. Clink item from toolbox add item to preview works fine, but dragging item to preview pane is buggy.

**Comment by dohoangtung** [comment]
Hi Kiho,

Issue1: I've double checked and it works fine, please try to restart the api service before testing
Iusse2: Yes, They are blocked currently, I will improve it
Issue 3: Yes, this is a bug. Will fix it!

Thanks,

**Comment by nhan2804** [comment]
@dohoangtung tks you for nice PR, I'm Vietnamese and i like this PR. you can give me contact . Facebook or zalo?

**Comment by dohoangtung** [comment]
> @dohoangtung tks you for nice PR, I'm Vietnamese and i like this PR. you can give me contact . Facebook or zalo?

Hi Nhan,

feel free to contact me at dohoangtung@gmail.com

**Comment by Kiho** [comment]
Thanks for PR, it's merged now.

**Pull request merged**
